# Generated by Django 6.0.4 on 2026-05-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow')], default='Black'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium')], default='M'),
        ),
    ]
