# Generated by Django 6.0.4 on 2026-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_products_colors_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.CharField(choices=[('White', 'W'), ('Black', 'B'), ('Red', 'R'), ('Blue', 'B'), ('Yellow', 'Y')], default='Black'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M')], default='M'),
        ),
    ]
